version: '3.8'

services:
  lingva-1:
    image: thedaviddelta/lingva-translate:latest
    container_name: lingva-1
    ports:
      - "3000:3000"
    restart: unless-stopped

  lingva-2:
    image: thedaviddelta/lingva-translate:latest
    container_name: lingva-2
    ports:
      - "3001:3000"
    restart: unless-stopped

  lingva-3:
    image: thedaviddelta/lingva-translate:latest
    container_name: lingva-3
    ports:
      - "3002:3000"
    restart: unless-stopped
